# Generated by Django 5.1.1 on 2024-09-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_size_remove_product_size_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
