# Generated by Django 5.1.1 on 2024-09-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='affiliate_link',
        ),
        migrations.AddField(
            model_name='product',
            name='amazon_affiliate_link',
            field=models.URLField(blank=True, null=True, verbose_name='Amazon'),
        ),
        migrations.AddField(
            model_name='product',
            name='meesho_affiliate_link',
            field=models.URLField(blank=True, null=True, verbose_name='Meesho'),
        ),
    ]
